param(
    [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\.."))
)

$ErrorActionPreference = "Stop"
$versionPath = Join-Path $ProjectRoot "Engine\Version\engine-version.json"
$version = Get-Content -LiteralPath $versionPath -Raw -Encoding UTF8 | ConvertFrom-Json
$validChannels = @("Stable", "Beta", "Dev")
if ($validChannels -notcontains $version.channel) {
    throw "Update Channel must be Stable, Beta, or Dev."
}
$scriptApiHeader = Get-Content -LiteralPath (Join-Path $ProjectRoot "Source\Engine\Core\EditorScriptApi.h") -Raw -Encoding UTF8
$scriptApiMatch = [regex]::Match($scriptApiHeader, 'kEditorScriptApiVersion\s*=\s*(\d+)U')
if (-not $scriptApiMatch.Success) { throw "kEditorScriptApiVersion was not found." }
$scriptApiVersion = [int]$scriptApiMatch.Groups[1].Value

$header = @"
#pragma once

#include <cstdint>

// Generated from Engine/Version/engine-version.json by Tools/Versioning/Sync-Version.ps1.
// Edit the JSON source only. Do not edit this file directly.
namespace CG2EngineVersionGenerated {
`tinline constexpr std::uint32_t kMajor = $($version.major)U;
`tinline constexpr std::uint32_t kMinor = $($version.minor)U;
`tinline constexpr std::uint32_t kPatch = $($version.patch)U;
`tinline constexpr std::uint32_t kBuild = $($version.build)U;
`tinline constexpr char kChannel[] = "$($version.channel)";
`tinline constexpr std::uint32_t kProjectFormat = $($version.projectFormat)U;
`tinline constexpr std::uint32_t kSceneFormat = $($version.sceneFormat)U;
`tinline constexpr std::uint32_t kPrefabFormat = $($version.prefabFormat)U;
}
"@

$display = "$($version.major).$($version.minor).$($version.patch)+$($version.build)"
$typescript = @"
// Generated from Engine/Version/engine-version.json. Do not edit directly.
export const engineVersion = {
  major: $($version.major),
  minor: $($version.minor),
  patch: $($version.patch),
  build: $($version.build),
  channel: "$($version.channel)",
  projectFormat: $($version.projectFormat),
  sceneFormat: $($version.sceneFormat),
  prefabFormat: $($version.prefabFormat),
  scriptApi: $scriptApiVersion,
  display: "$display",
} as const;
"@

$utf8Bom = New-Object System.Text.UTF8Encoding($true)
$headerPath = Join-Path $ProjectRoot "Source\Engine\Core\EngineVersion.generated.h"
$typescriptPath = Join-Path $ProjectRoot "site\app\generated\engineVersion.ts"
$mutex = New-Object System.Threading.Mutex($false, "Local\CG2EngineVersionSync")
$hasMutex = $false
try {
    try { $hasMutex = $mutex.WaitOne([TimeSpan]::FromSeconds(30)) }
    catch [System.Threading.AbandonedMutexException] { $hasMutex = $true }
    if (-not $hasMutex) { throw "Timed out waiting for the CG2Engine version sync lock." }
    [System.IO.Directory]::CreateDirectory([System.IO.Path]::GetDirectoryName($typescriptPath)) | Out-Null
    [System.IO.File]::WriteAllText($headerPath, $header, $utf8Bom)
    [System.IO.File]::WriteAllText($typescriptPath, $typescript, $utf8Bom)
}
finally {
    if ($hasMutex) { $mutex.ReleaseMutex() }
    $mutex.Dispose()
}
Write-Host "Synced CG2Engine $display / Script API $scriptApiVersion"
